### ISSUE TITLE
.names file

### ISSUE THREAD

**Issue by azim92** [akarshzingade/Logo-Detection-YOLOv2#1]
Hello, may I know which .names file you used for the logo detection?
Or do you follow @alaxeyAB guide to create the names file?

**Comment by akarshzingade** [comment]
Hey Azim. I have uploaded the names file [here](https://github.com/akarshzingade/Logo-Detection-YOLOv2/blob/master/obj.names). And yes, I did follow AlexeyAB's instructions to create the file. :)

**Comment by azim92** [comment]
noted, thank you for your assist. Best regards!
